# Site settings
title: mrloop
email: info@mrloop.com
description: > # this means to ignore newlines until "baseurl:"
  News and Stories from mrloop, avid cyclist, coder, maker of picturewham.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://blog.mrloop.com" # the base hostname & protocol for your site
author: mrloop
logo: /images/logo.png
twitter_username: mrloop
github_username:  mrloop
lang: en-GB

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

plugins:
  - jekyll-seo-tag
  - jekyll-feed
